import { Account, Category, Transaction, Budget, Goal, DashboardSummary, CreditCard, CardInvoice } from '@/types';

export const mockUser = {
  id: '1',
  email: 'dudiafinance@yahoo.com',
  name: 'Eduardo',
  avatar: '',
  currency: 'BRL',
  locale: 'pt-BR',
  timezone: 'America/Sao_Paulo',
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const mockAccounts: Account[] = [
  {
    id: '1',
    userId: '1',
    name: 'Nubank',
    type: 'checking',
    bank: 'Nubank',
    balance: 15420.50,
    currency: 'BRL',
    color: '#820AD1',
    icon: 'credit-card',
    isActive: true,
    includeInTotal: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    userId: '1',
    name: 'Itaú',
    type: 'checking',
    bank: 'Itaú',
    balance: 8750.00,
    currency: 'BRL',
    color: '#EC7000',
    icon: 'building',
    isActive: true,
    includeInTotal: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    userId: '1',
    name: 'Carteira',
    type: 'checking',
    balance: 500.00,
    currency: 'BRL',
    color: '#10B981',
    icon: 'wallet',
    isActive: true,
    includeInTotal: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    userId: '1',
    name: 'Cartão Nubank',
    type: 'credit_card',
    balance: -2350.00,
    currency: 'BRL',
    color: '#820AD1',
    icon: 'credit-card',
    isActive: true,
    includeInTotal: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockCategories: Category[] = [
  { id: '1', userId: '1', name: 'Salário', type: 'income', icon: 'briefcase', color: '#10B981', isActive: true, order: 0, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '2', userId: '1', name: 'Freelance', type: 'income', icon: 'laptop', color: '#3B82F6', isActive: true, order: 1, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '3', userId: '1', name: 'Investimentos', type: 'income', icon: 'trending-up', color: '#8B5CF6', isActive: true, order: 2, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '4', userId: '1', name: 'Alimentação', type: 'expense', icon: 'coffee', color: '#EF4444', isActive: true, order: 0, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '5', userId: '1', name: 'Transporte', type: 'expense', icon: 'car', color: '#F59E0B', isActive: true, order: 1, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '6', userId: '1', name: 'Moradia', type: 'expense', icon: 'home', color: '#6366F1', isActive: true, order: 2, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '7', userId: '1', name: 'Lazer', type: 'expense', icon: 'film', color: '#EC4899', isActive: true, order: 3, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '8', userId: '1', name: 'Saúde', type: 'expense', icon: 'heart', color: '#14B8A6', isActive: true, order: 4, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '9', userId: '1', name: 'Educação', type: 'expense', icon: 'book', color: '#845EF7', isActive: true, order: 5, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '10', userId: '1', name: 'Outros', type: 'expense', icon: 'more-horizontal', color: '#64748B', isActive: true, order: 6, tags: [], createdAt: new Date(), updatedAt: new Date() },
];

export const mockTransactions: Transaction[] = [
  { id: '1', userId: '1', accountId: '1', categoryId: '1', amount: 8500.00, type: 'income', date: new Date('2026-04-01'), description: 'Salário Março', isRecurring: true, isPaid: true, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '2', userId: '1', accountId: '1', categoryId: '2', amount: 2500.00, type: 'income', date: new Date('2026-04-03'), description: 'Projeto Site', isRecurring: false, isPaid: true, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '3', userId: '1', accountId: '1', categoryId: '4', amount: 450.00, type: 'expense', date: new Date('2026-04-02'), description: 'Supermercado', isRecurring: false, isPaid: true, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '4', userId: '1', accountId: '1', categoryId: '5', amount: 120.00, type: 'expense', date: new Date('2026-04-02'), description: 'Uber', isRecurring: false, isPaid: true, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '5', userId: '1', accountId: '1', categoryId: '6', amount: 1500.00, type: 'expense', date: new Date('2026-04-05'), description: 'Aluguel', isRecurring: true, isPaid: true, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '6', userId: '1', accountId: '1', categoryId: '7', amount: 89.90, type: 'expense', date: new Date('2026-04-04'), description: 'Netflix + Spotify', isRecurring: true, isPaid: true, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '7', userId: '1', accountId: '1', categoryId: '8', amount: 180.00, type: 'expense', date: new Date('2026-04-01'), description: 'Farmácia', isRecurring: false, isPaid: true, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '8', userId: '1', accountId: '1', categoryId: '9', amount: 120.00, type: 'expense', date: new Date('2026-04-01'), description: 'Curso Udemy', isRecurring: false, isPaid: true, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '9', userId: '1', accountId: '1', categoryId: '10', amount: 250.00, type: 'expense', date: new Date('2026-04-03'), description: 'Outros', isRecurring: false, isPaid: true, tags: [], createdAt: new Date(), updatedAt: new Date() },
  { id: '10', userId: '1', accountId: '4', categoryId: '4', amount: 180.00, type: 'expense', date: new Date('2026-04-05'), description: 'Ifood', isRecurring: false, isPaid: true, tags: [], createdAt: new Date(), updatedAt: new Date() },
];

export const mockBudgets: Budget[] = [
  { id: '1', userId: '1', categoryId: '4', name: 'Alimentação', amount: 1500.00, period: 'monthly', startDate: new Date('2026-04-01'), isActive: true, alertsEnabled: true, alertThreshold: 80, createdAt: new Date(), updatedAt: new Date() },
  { id: '2', userId: '1', categoryId: '5', name: 'Transporte', amount: 500.00, period: 'monthly', startDate: new Date('2026-04-01'), isActive: true, alertsEnabled: true, alertThreshold: 80, createdAt: new Date(), updatedAt: new Date() },
  { id: '3', userId: '1', categoryId: '7', name: 'Lazer', amount: 300.00, period: 'monthly', startDate: new Date('2026-04-01'), isActive: true, alertsEnabled: true, alertThreshold: 80, createdAt: new Date(), updatedAt: new Date() },
];

export const mockGoals: Goal[] = [
  { id: '1', userId: '1', name: 'Reserva de Emergência', targetAmount: 20000.00, currentAmount: 8500.00, deadline: new Date('2026-12-31'), status: 'active', priority: 'high', createdAt: new Date(), updatedAt: new Date() },
  { id: '2', userId: '1', name: 'Viagem Japão', targetAmount: 15000.00, currentAmount: 3200.00, deadline: new Date('2027-06-01'), status: 'active', priority: 'medium', createdAt: new Date(), updatedAt: new Date() },
  { id: '3', userId: '1', name: 'Novo Carro', targetAmount: 80000.00, currentAmount: 15000.00, deadline: new Date('2028-01-01'), status: 'active', priority: 'low', createdAt: new Date(), updatedAt: new Date() },
];

export const mockDashboardSummary: DashboardSummary = {
  totalBalance: 24320.50,
  totalIncome: 11000.00,
  totalExpense: 4289.90,
  monthlyVariation: 12.5,
};

export const mockIncomeByCategory = [
  { name: 'Salário', value: 8500 },
  { name: 'Freelance', value: 2500 },
];

export const mockExpenseByCategory = [
  { name: 'Alimentação', value: 630, color: '#EF4444' },
  { name: 'Moradia', value: 1500, color: '#6366F1' },
  { name: 'Transporte', value: 120, color: '#F59E0B' },
  { name: 'Lazer', value: 89.90, color: '#EC4899' },
  { name: 'Saúde', value: 180, color: '#14B8A6' },
  { name: 'Educação', value: 120, color: '#845EF7' },
  { name: 'Outros', value: 250, color: '#64748B' },
];

export const mockMonthlyData = [
  { month: 'Jan', income: 8500, expense: 3200 },
  { month: 'Fev', income: 8500, expense: 4100 },
  { month: 'Mar', income: 11000, expense: 3800 },
  { month: 'Abr', income: 11000, expense: 4290 },
];

export const mockCreditCards: CreditCard[] = [
  {
    id: 'cc1',
    userId: '1',
    name: 'Nubank Ultravioleta',
    bank: 'Nubank',
    lastDigits: '4892',
    limit: 15000,
    usedAmount: 3847.50,
    dueDay: 10,
    closingDay: 3,
    color: '#820AD1',
    gradient: 'from-[#820AD1] to-[#4B0082]',
    network: 'mastercard',
    isActive: true,
  },
  {
    id: 'cc2',
    userId: '1',
    name: 'Itaú Personnalité',
    bank: 'Itaú',
    lastDigits: '7731',
    limit: 20000,
    usedAmount: 7210.00,
    dueDay: 15,
    closingDay: 8,
    color: '#EC7000',
    gradient: 'from-[#EC7000] to-[#B35400]',
    network: 'visa',
    isActive: true,
  },
  {
    id: 'cc3',
    userId: '1',
    name: 'C6 Carbon',
    bank: 'C6 Bank',
    lastDigits: '2204',
    limit: 8000,
    usedAmount: 1250.00,
    dueDay: 20,
    closingDay: 13,
    color: '#1A1A1A',
    gradient: 'from-[#2D2D2D] to-[#0A0A0A]',
    network: 'mastercard',
    isActive: true,
  },
];

export const mockCardInvoices: CardInvoice[] = [
  {
    id: 'inv1',
    cardId: 'cc1',
    month: 'Abril',
    year: 2026,
    total: 3847.50,
    status: 'open',
    dueDate: new Date('2026-04-10'),
    transactions: [
      { id: 'ct1', cardId: 'cc1', description: 'iFood', categoryId: '4', amount: 87.50, date: new Date('2026-04-01'), isPending: false },
      { id: 'ct2', cardId: 'cc1', description: 'Amazon', categoryId: '10', amount: 349.90, date: new Date('2026-04-02'), installments: 3, currentInstallment: 1, isPending: false },
      { id: 'ct3', cardId: 'cc1', description: 'Posto Shell', categoryId: '5', amount: 250.00, date: new Date('2026-04-02'), isPending: false },
      { id: 'ct4', cardId: 'cc1', description: 'Farmácias Pague Menos', categoryId: '8', amount: 145.00, date: new Date('2026-04-03'), isPending: false },
      { id: 'ct5', cardId: 'cc1', description: 'Netflix', categoryId: '7', amount: 55.90, date: new Date('2026-04-03'), isRecurring: true, isPending: false } as any,
      { id: 'ct6', cardId: 'cc1', description: 'Spotify', categoryId: '7', amount: 21.90, date: new Date('2026-04-03'), isPending: false },
      { id: 'ct7', cardId: 'cc1', description: 'Supermercado Extra', categoryId: '4', amount: 412.30, date: new Date('2026-04-04'), isPending: false },
      { id: 'ct8', cardId: 'cc1', description: 'Dentista', categoryId: '8', amount: 350.00, date: new Date('2026-04-04'), installments: 2, currentInstallment: 1, isPending: false },
      { id: 'ct9', cardId: 'cc1', description: 'Zara', categoryId: '10', amount: 289.00, date: new Date('2026-04-05'), isPending: false },
      { id: 'ct10', cardId: 'cc1', description: 'Rappi', categoryId: '4', amount: 63.50, date: new Date('2026-04-05'), isPending: true },
      { id: 'ct11', cardId: 'cc1', description: 'Uber', categoryId: '5', amount: 38.90, date: new Date('2026-04-05'), isPending: true },
      { id: 'ct12', cardId: 'cc1', description: 'Cinema', categoryId: '7', amount: 72.00, date: new Date('2026-04-04'), isPending: false },
      { id: 'ct13', cardId: 'cc1', description: 'Academia SmartFit', categoryId: '8', amount: 109.90, date: new Date('2026-04-01'), isPending: false },
      { id: 'ct14', cardId: 'cc1', description: 'Livros Amazon', categoryId: '9', amount: 89.90, date: new Date('2026-04-03'), isPending: false },
      { id: 'ct15', cardId: 'cc1', description: 'Restaurante', categoryId: '4', amount: 212.00, date: new Date('2026-04-02'), isPending: false },
      { id: 'ct16', cardId: 'cc1', description: 'Mercado Livre', categoryId: '10', amount: 498.70, date: new Date('2026-04-01'), installments: 5, currentInstallment: 3, isPending: false },
      { id: 'ct17', cardId: 'cc1', description: 'Conta de Luz', categoryId: '6', amount: 180.00, date: new Date('2026-04-01'), isPending: false },
      { id: 'ct18', cardId: 'cc1', description: 'Internet Vivo', categoryId: '6', amount: 119.90, date: new Date('2026-04-01'), isPending: false },
    ],
  },
  {
    id: 'inv2',
    cardId: 'cc1',
    month: 'Março',
    year: 2026,
    total: 4120.00,
    status: 'paid',
    dueDate: new Date('2026-03-10'),
    transactions: [],
  },
  {
    id: 'inv3',
    cardId: 'cc1',
    month: 'Fevereiro',
    year: 2026,
    total: 3650.00,
    status: 'paid',
    dueDate: new Date('2026-02-10'),
    transactions: [],
  },
  {
    id: 'inv4',
    cardId: 'cc1',
    month: 'Janeiro',
    year: 2026,
    total: 2890.00,
    status: 'paid',
    dueDate: new Date('2026-01-10'),
    transactions: [],
  },
  {
    id: 'inv5',
    cardId: 'cc1',
    month: 'Dezembro',
    year: 2025,
    total: 5200.00,
    status: 'paid',
    dueDate: new Date('2025-12-10'),
    transactions: [],
  },
  {
    id: 'inv6',
    cardId: 'cc1',
    month: 'Novembro',
    year: 2025,
    total: 3100.00,
    status: 'paid',
    dueDate: new Date('2025-11-10'),
    transactions: [],
  },
];
